save_dir: workspace/anpr_desktop
model:
  qat: False # Quantization Aware Training
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 100
    backbone:
      name: MobileNetV4
      block_size: small
      width_mult: 1.0
      out_stages: [2,3,5]
      activation: ReLU
    fpn:
      name: GhostPAN
      in_channels: [64, 96, 960]
      out_channels: 96
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: True
      activation: LeakyReLU
      upsample_cfg: 
        scale_factor: 2.0
        mode: 'bilinear'
    head:
      name: NanoDetPlusHead
      num_classes: 2
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 9
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 2
      input_channel: 192
      feat_channels: 192
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 9
data:
  train:
    name: CocoDataset
    img_path: datasets/anpr_main/coco/train2017
    ann_path: datasets/anpr_main/coco/annotations/instances_train.json
    input_size: [640,640] #[w,h]
    keep_ratio: False
    pipeline:
      # Geometry
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 5
      shear: 0
      translate: 0.2
      flip: 0.5
      # Texture
      average_blur: [3, 9]
      gaussian_blur: [0.0, 3.0]
      motion_blur: [15, -45, 45]
      multiply: [0.5, 1.5]
      multiply_hue: [0.5, 1.5]
      multiply_saturation: [0.5, 1.5]
      gamma_contrast: [0.5, 2.0]
      sigmoid_contrast: [3, 10, 0.4, 0.6]
      log_contrast: [0.6, 1.4]
      linear_contrast: [0.5, 1.5]
      emboss: [0, 1.0, 0, 2.0]
      additive_gaussian_noise: 10.0
      salt: 0.02
      pepper: 0.02
      normalize: [[123.675, 116.28, 103.53], [58.395, 57.12, 57.375]]
  val:
    name: CocoDataset
    img_path: datasets/anpr_main/coco/val2017
    ann_path: datasets/anpr_main/coco/annotations/instances_val.json
    input_size: [640,640] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [[123.675, 116.28, 103.53], [58.395, 57.12, 57.375]]
device:
  gpu_ids: [0,1]
  workers_per_gpu: 32
  batchsize_per_gpu: 30
  precision: 32 # set to 16 to use AMP training
schedule:
  #resume:
  load_model: workspace/anpr_desktop/model_best/model_best.ckpt
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 300
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
  val_intervals: 1
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 10

class_names: ['plate', 'car']
