# nanodet-plus-m_416
# COCO mAP(0.5:0.95) = 0.304
#             AP_50  = 0.459
#             AP_75  = 0.317
#           AP_small = 0.106
#               AP_m = 0.322
#               AP_l = 0.477
save_dir: workspace/mobilenetv2
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 100
    backbone:
      name: MobileNetV2
      width_mult: 0.15
      out_stages: [2,4,6]
      activation: LeakyReLU
      last_channel: 1280
    fpn:
      name: GhostPAN
      in_channels: [4,14,1280] # 1.0=[32,96,1280], 0.5=[16,48,1280], 0.25=[8,24,1280], 0.15=[4,14,1280]
      out_channels: 96
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: True
      activation: LeakyReLU
    head:
      name: NanoDetPlusHead
      num_classes: 2
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 9
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 2
      input_channel: 192
      feat_channels: 192
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 9
data:
  train:
    name: CocoDataset
    img_path: datasets/coco/train2017
    ann_path: datasets/coco/annotations/instances_train.json
    input_size: [640,640] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[123.675, 116.28, 103.53], [58.395, 57.12, 57.375]]
  val:
    name: CocoDataset
    img_path: datasets/coco/val2017
    ann_path: datasets/coco/annotations/instances_val.json
    input_size: [640,640] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [[123.675, 116.28, 103.53], [58.395, 57.12, 57.375]]
device:
  gpu_ids: [0,1]
  workers_per_gpu: 10
  batchsize_per_gpu: 45
  precision: 32 # set to 16 to use AMP training
schedule:
  #resume:
  #load_model: workspace/mobilenetv2/model_best/model_best.ckpt
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 300
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
  val_intervals: 1
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 10

class_names: ['plate', 'car']
